name: Build

on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://testdemo.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  GIT_COMMIT: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  test:
    name: "Build and Test (dotnet)"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["8.0.x"]
        pact_provider:
          [
            # "pactflow-example-bi-directional-provider-dredd",
            # "pactflow-example-bi-directional-provider-restassured",
            # "pactflow-example-bi-directional-provider-postman",
            # "pactflow-example-provider",
            'pactflow-provider-dotnet'
          ]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: test for ${{ matrix.pact_provider }}
        run: GIT_BRANCH=${GITHUB_REF:11} make test
        env:
          PACT_PROVIDER: ${{ matrix.pact_provider }}
      - name: Publish pacts for ${{ matrix.pact_provider }}
        run: GIT_BRANCH=${GITHUB_REF:11} make publish_pacts
        env:
          PACT_PROVIDER: ${{ matrix.pact_provider }}
        

  # Runs on branches as well, so we know the status of our PRs
  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Can I deploy?
        run: GIT_BRANCH=${GITHUB_REF:11} make can_i_deploy

  # Only deploy from main
  deploy:
    runs-on: ubuntu-latest
    needs: can-i-deploy
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Deploy
        run: GIT_BRANCH=${GITHUB_REF:11} make deploy
        if: github.ref == 'refs/heads/main'